import { IClass } from "./class.types.js"


export const CLASSES: Record<string, IClass> = {
    farmer: {
        id: 'farmer',
        name: 'Fazendeiro',
        description: 'Mestre da terra. Faz plantações crescerem mais rápido e com maior rendimento.',
        emoji: '🌾',
        strBonus: 1,
        intBonus: 0,
        agiBonus: 0,
        chaBonus: 0,
        endBonus: 2,
        luckBonus: 1,
        expMultiplier: 1.0,
        moneyMultiplier: 1.1,
    },
    businessman: {
        id: 'businessman',
        name: 'Empresário',
        description: 'Tudo gira em torno do dinheiro. Ganha mais em todo tipo de transação.',
        emoji: '💼',
        strBonus: 0,
        intBonus: 2,
        agiBonus: 0,
        chaBonus: 2,
        endBonus: 0,
        luckBonus: 0,
        expMultiplier: 1.0,
        moneyMultiplier: 1.25,
    },
    builder: {
        id: 'builder',
        name: 'Construtor',
        description: 'Constrói mais barato e melhor. Casas e propriedades têm mais valor.',
        emoji: '🔨',
        strBonus: 3,
        intBonus: 1,
        agiBonus: 0,
        chaBonus: 0,
        endBonus: 2,
        luckBonus: 0,
        expMultiplier: 1.0,
        moneyMultiplier: 1.0,
    },
    herbalist: {
        id: 'herbalist',
        name: 'Herbalista',
        description: 'Conhece os segredos das plantas. Produz itens raros e poções potentes.',
        emoji: '🌿',
        strBonus: 0,
        intBonus: 3,
        agiBonus: 1,
        chaBonus: 0,
        endBonus: 0,
        luckBonus: 2,
        expMultiplier: 1.1,
        moneyMultiplier: 1.0,
    },
    diplomat: {
        id: 'diplomat',
        name: 'Diplomata',
        description: 'Carisma acima de tudo. Relações sociais são mais fáceis e lucrativas.',
        emoji: '🎭',
        strBonus: 0,
        intBonus: 1,
        agiBonus: 0,
        chaBonus: 4,
        endBonus: 0,
        luckBonus: 1,
        expMultiplier: 1.0,
        moneyMultiplier: 1.15,
    },
    miner: {
        id: 'miner',
        name: 'Minerador',
        description: 'Extrai mais recursos e encontra materiais raros ao explorar.',
        emoji: '⛏️',
        strBonus: 3,
        intBonus: 0,
        agiBonus: 0,
        chaBonus: 0,
        endBonus: 3,
        luckBonus: 0,
        expMultiplier: 1.0,
        moneyMultiplier: 1.0,
    },
    adventurer: {
        id: 'adventurer',
        name: 'Aventureiro',
        description: 'Nasceu para explorar. Viagens mais baratas e eventos especiais pelo mundo.',
        emoji: '🏹',
        strBonus: 1,
        intBonus: 1,
        agiBonus: 3,
        chaBonus: 0,
        endBonus: 0,
        luckBonus: 1,
        expMultiplier: 1.1,
        moneyMultiplier: 1.0,
    },
    sage: {
        id: 'sage',
        name: 'Sábio',
        description: 'Aprende mais rápido que qualquer outro. Ganha +15% de EXP em tudo.',
        emoji: '📚',
        strBonus: 0,
        intBonus: 4,
        agiBonus: 0,
        chaBonus: 0,
        endBonus: 0,
        luckBonus: 2,
        expMultiplier: 1.15,
        moneyMultiplier: 1.0,
    },
}

export const CLASS_IDS = Object.keys(CLASSES)